export const SYSTEM_CONSTANTS = {
  SUPER_ADMIN_USER_ID: 1,
  SUPER_ADMIN_ROLE_ID: 1,
  MENU_VISIBLE: 1,
  MENU_HIDDEN: 0,
  DELETED_NO: 0,
  DELETED_YES: 1,
  STATUS_ENABLE: 1,
  STATUS_DISABLE: 0,
  ROOT_MENU_PARENT_ID: 0
}

export default SYSTEM_CONSTANTS